---
- hosts: server
  become: true

  tasks:
    - name: Ensure Java Runtime Environment is installed
      yum:
        name: java-17-openjdk-headless
        state: present

    - name: Make sure minecraft group exists
      group:
        name: minecraft

    - name: Make sure mehdi is part of minecraft group
      user:
        name: mehdi
        append: true
        groups: minecraft

    - name: Ensure minecraft user exists with it's home directory
      user:
        name: minecraft
        password: '!'
        create_home: true
        home: /opt/minecraft
        groups: minecraft

    - name: Make sure to be able to ssh to minecraft user
      authorized_key:
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        user: minecraft

    # for the following you need to have the server jar and the eula.txt file
    # in the serverFiles directory

    # Execute the server for the first time to get the eula.txt file and
    # change the line "eula=false" to "eula=true" to indicate that you except
    # the Minecraft End User License Agreement.

    - name: Ensure the Minecraft server related files are copied to the server
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: minecraft
        mode: "{{ item.mode }}"

      with_items:

        # Server jar file
        - src: ./serverFiles/server.jar
          dest: /opt/minecraft/server.jar
          mode: '0444'

        # The eula file
        - src: ./serverFiles/eula.txt
          dest: /opt/minecraft/eula.txt
          mode: '0664'

        # The properties file
        - src: ./serverFiles/server.properties
          dest: /opt/minecraft/server.properties
          mode: '0664'

        # The script that runs the server
        - src: ./runServer.sh
          dest: /opt/minecraft/runServer.sh
          mode: '0554'

        # The systemd service configuration file
        - src: ./minecraft.service
          dest: /etc/systemd/system/minecraft.service
          mode: '0444'

    - name: Ensure port 25565 (TCP and UDP) is not permanently open
      firewalld:
        port: "{{ item.port }}"
        permanent: false
        state: disabled

      with_items:
        - port: '25565/tcp'
        - port: '25565/udp'

    - name: Ensure the Minecraft server service does not start at boot
      service:
        name: minecraft
        enabled: false

